# This file was *autogenerated* from the file VectorGraph2.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_0p1 = RealNumber('0.1'); _sage_const_25 = Integer(25)#!/usr/bin/env sage

# the points
points = [(_sage_const_2 ,_sage_const_4 ), (-_sage_const_3 ,_sage_const_4 ), (-_sage_const_5 ,-_sage_const_1 ), (_sage_const_5 ,-_sage_const_3 )]

# This next little bit constructs the labels for the points
labels = []                     # This is the list of labels.

# Loop through the points
for point in points:
    # The label needs to be slightly to the right of the point, as to
    # not overwrite it.
    newpoint = (point[_sage_const_0 ] + _sage_const_0p1 , point[_sage_const_1 ])
    # This label will just have the coordinate listed, with some
    # styling.
    this_label = text("$"+str(point)+"$", newpoint, fontsize=_sage_const_25 ,
                      rgbcolor=(_sage_const_0 ,_sage_const_0 ,_sage_const_0 ), horizontal_alignment="left")

    # Add this label to the list.
    labels.append(this_label)
labels = sum(labels)

# A plot of the points
myticks = [range(-_sage_const_100 ,_sage_const_100 )] * _sage_const_2 
pts = list_plot(points, 
                ticks=myticks,
                tick_formatter="latex",
                pointsize=_sage_const_25 ,
                axes_labels = ['$x$', '$y$']
               ) + labels
pts.set_axes_range(-_sage_const_6 ,_sage_const_6 ,-_sage_const_4 ,_sage_const_5 )
pts.fontsize(_sage_const_25 )
# Save it to a file
pts.save("VectorGraph2.png")
