# This file was *autogenerated* from the file x-squared.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_110 = Integer(110); _sage_const_0p3 = RealNumber('0.3'); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_140 = Integer(140); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20); _sage_const_25 = Integer(25)#!/usr/bin/env sage

from numpy import arange

squarelist = []
textlist = []

for x in arange(-_sage_const_10 ,_sage_const_11 ):
    t = text('$' + str((x, x**_sage_const_2 )) + '$',
             (x+_sage_const_0p3 , x**_sage_const_2 ),
             rgbcolor='black',
             horizontal_alignment='left'
            )
    squarelist.append((x,x**_sage_const_2 ))
    textlist.append(t)

pts = list_plot(squarelist,
                ticks=_sage_const_2 ,
                tick_formatter=_sage_const_1 ,
                pointsize=_sage_const_15 ,
                color='red',
                axes_labels=['$x$', '$f(x)$']
               )
pts.set_axes_range(xmin=-_sage_const_11 , xmax=_sage_const_11 , ymin=-_sage_const_10 , ymax=_sage_const_110 )
pts.fontsize(_sage_const_15 )
pts.save("x-squared-nolabels.png")

# Add labels
pts_with_labels = pts + sum(textlist)
pts_with_labels.save("x-squared-labels.png")

# Add connecting lines
pts_with_conn = pts_with_labels + list_plot(squarelist, plotjoined=True)
pts_with_conn.save("x-squared-joined.png")

# Add Curve
x=var('x')
pts_with_curve = pts + plot(x**_sage_const_2 , (x, -_sage_const_11 , _sage_const_11 ), color='green')
pts_with_curve.save("x-squared-withcurve-nolabels.png")

curve = plot(x**_sage_const_2 , (x, -_sage_const_11 , _sage_const_11 ),
             color='green',
             ticks=[list(arange(-_sage_const_20 ,_sage_const_20 ,_sage_const_2 )), list(arange(_sage_const_0 ,_sage_const_140 ,_sage_const_20 ))],
             thickness=_sage_const_5 ,
             axes_labels=['$x$', '$y$'])
             # legend_label='$\\lambda (x) \\to x^2$')
curve.fontsize(_sage_const_25 )
curve.save("x-squared-curve.png")
